" Vim configuration.
" Link or symlink to ~/.vimrc or ~/_vimrc.

set nocompatible                  " Must come first because it changes other options.

syntax enable                     " Turn on syntax highlighting.
filetype plugin indent on         " Turn on file type detection.

"set showcmd                           " Display incomplete commands.
"set showmode                          " Display the mode you're in.

set backspace=indent,eol,start        " Intuitive backspacing.

set hidden                            " Handle multiple buffers better.

set wildmenu                          " Enhanced command line completion.
set wildmode=list:longest             " Complete files like a shell.

set ignorecase                        " Case-insensitive searching.
set smartcase                         " But case-sensitive if expression contains a capital letter.

"set autoindent                       " always set autoindenting on
"set copyindent                       " copy the previous indentation on autoindenting

set number                            " Show line numbers.
"set relativenumber                   " Show relative line numbers.

set ruler

" makes vim slow as hell
"set cursorline                        " Show cursor position.

set incsearch                         " Highlight matches as you type.
set hlsearch                          " Highlight matches.

set scrolloff=0                       " Show 3 lines of context around the cursor.

set title                             " Set the terminal's title

set visualbell                        " No beeping.

"set nobackup                          " Don't make a backup before overwriting a file.
"set nowritebackup                     " And again.

set history=1000                            " remember more commands and search history
set undolevels=1000                         " use many muchos levels of undo
set wildignore=*.swp,*.bak,*.pyc,*.class,target


set tabstop=2                    " Global tab width.
set shiftwidth=2                 " And again, related.
set softtabstop=2
set expandtab                    " Use spaces instead of tabs

set laststatus=2                  " Show the status line all the time

set nowrap "do not wrap lines

set linebreak

"set undofile



